//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalBakeMVCFront.WcfPriceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfPriceService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateOrderPrice", ReplyAction="http://tempuri.org/IService/CalculateOrderPriceResponse")]
        decimal CalculateOrderPrice(System.Collections.Generic.Dictionary<string, int> orderList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateOrderPrice", ReplyAction="http://tempuri.org/IService/CalculateOrderPriceResponse")]
        System.Threading.Tasks.Task<decimal> CalculateOrderPriceAsync(System.Collections.Generic.Dictionary<string, int> orderList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPrice", ReplyAction="http://tempuri.org/IService/GetPriceResponse")]
        decimal GetPrice(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPrice", ReplyAction="http://tempuri.org/IService/GetPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetPriceAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllPrices", ReplyAction="http://tempuri.org/IService/GetAllPricesResponse")]
        Metal_Bake.Infra.WcfPriceReference.ItemPrice[] GetAllPrices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllPrices", ReplyAction="http://tempuri.org/IService/GetAllPricesResponse")]
        System.Threading.Tasks.Task<Metal_Bake.Infra.WcfPriceReference.ItemPrice[]> GetAllPricesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetPrice", ReplyAction="http://tempuri.org/IService/SetPriceResponse")]
        decimal SetPrice(Metal_Bake.Infra.WcfPriceReference.ItemPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetPrice", ReplyAction="http://tempuri.org/IService/SetPriceResponse")]
        System.Threading.Tasks.Task<decimal> SetPriceAsync(Metal_Bake.Infra.WcfPriceReference.ItemPrice item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TxtListPrice", ReplyAction="http://tempuri.org/IService/TxtListPriceResponse")]
        void TxtListPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TxtListPrice", ReplyAction="http://tempuri.org/IService/TxtListPriceResponse")]
        System.Threading.Tasks.Task TxtListPriceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MetalBakeMVCFront.WcfPriceService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MetalBakeMVCFront.WcfPriceService.IService>, MetalBakeMVCFront.WcfPriceService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CalculateOrderPrice(System.Collections.Generic.Dictionary<string, int> orderList) {
            return base.Channel.CalculateOrderPrice(orderList);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateOrderPriceAsync(System.Collections.Generic.Dictionary<string, int> orderList) {
            return base.Channel.CalculateOrderPriceAsync(orderList);
        }
        
        public decimal GetPrice(string key) {
            return base.Channel.GetPrice(key);
        }
        
        public System.Threading.Tasks.Task<decimal> GetPriceAsync(string key) {
            return base.Channel.GetPriceAsync(key);
        }
        
        public Metal_Bake.Infra.WcfPriceReference.ItemPrice[] GetAllPrices() {
            return base.Channel.GetAllPrices();
        }
        
        public System.Threading.Tasks.Task<Metal_Bake.Infra.WcfPriceReference.ItemPrice[]> GetAllPricesAsync() {
            return base.Channel.GetAllPricesAsync();
        }
        
        public decimal SetPrice(Metal_Bake.Infra.WcfPriceReference.ItemPrice item) {
            return base.Channel.SetPrice(item);
        }
        
        public System.Threading.Tasks.Task<decimal> SetPriceAsync(Metal_Bake.Infra.WcfPriceReference.ItemPrice item) {
            return base.Channel.SetPriceAsync(item);
        }
        
        public void TxtListPrice() {
            base.Channel.TxtListPrice();
        }
        
        public System.Threading.Tasks.Task TxtListPriceAsync() {
            return base.Channel.TxtListPriceAsync();
        }
    }
}
